//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.OrdenProducto = new HashSet<OrdenProducto>();
        }
    
        public int id_orden { get; set; }
        public decimal total { get; set; }
        public string metodo_pago { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal descuento { get; set; }
        public string comentarios { get; set; }
        public Nullable<int> id_mesa { get; set; }
        public Nullable<int> id_trabajador { get; set; }
        public bool activa { get; set; }
    
        public virtual Mesa Mesa { get; set; }
        public virtual Trabajador Trabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenProducto> OrdenProducto { get; set; }
    }
}
