//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        public int id_reservacion { get; set; }
        public int id_mesa { get; set; }
        public int id_cliente { get; set; }
        public System.DateTime hora_inicio { get; set; }
        public System.DateTime hora_fin { get; set; }
        public bool activa { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Mesa Mesa { get; set; }
    }
}
