//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id_trabajador { get; set; }
        public string username { get; set; }
        public byte[] hash { get; set; }
        public byte[] salt { get; set; }
        public string api_key { get; set; }
    
        public virtual Trabajador Trabajador { get; set; }
    }
}
